#!/usr/bin/bash


# stanza="interface FastEthernet0/1
# switchport trunk allowed vlan remove 1002
# switchport trunk allowed vlan remove 1003
# switchport trunk allowed vlan remove 1004
# switchport trunk allowed vlan remove 1005
# exit"

# cat <<< $stanza

vlan_ids=(1 100{2,3,4,5})

# Habilita modo privilegiado
echo enable

# Entra no modo de configuração
echo configure terminal

# Derrubar todas as portas
echo interface range FastEthernet0/1-24
echo shutdown
echo -e "exit\n"

# Joga a porta 18 em Access
echo interface FastEthernet0/18
echo switchport mode access
echo -e "exit\n"

# Joga todas as portas em Trunk exceto a 18
echo interface range FastEthernet0/1-17
echo switchport mode trunk
echo interface range FastEthernet0/19-24
echo switchport mode trunk
echo -e "exit\n"

# Remove VLANs padrão de todas as portas
# echo interface range FastEthernet0/1-24
# for vlan in ${vlan_ids[@]}; do
#     echo "switchport trunk allowed vlan remove $vlan"
# done
# echo -e "exit\n"

# Cria uma nova VLAN 10
echo vlan 10
echo name REDE_SALA
echo -e "exit\n"

# Remove todas as portas da VLAN 10
echo interface range FastEthernet0/1-24
echo switchport trunk allowed vlan remove 10
echo -e "exit\n"

# Adicionar portas de computadores em VLAN 10
# Configuração extra do ultimo Switch requer alterar de 5 para 8
echo interface range FastEthernet0/1-5
echo switchport trunk allowed vlan add 10
echo -e "exit\n"

# Configurar portas de duplas 10Mb/Half
echo interface range FastEthernet0/1-2
echo speed 10
echo duplex half
echo -e "exit\n"

# Configurar portas de trios 10Mb/Full
# Configuração extra do ultimo Switch requer alterar de 5 para 8
echo interface range FastEthernet0/3-5
echo speed 10
echo duplex full
echo -e "exit\n"

# Configurar a porta do AP como auto
# echo interface FastEthernet0/20
# echo speed auto
# echo duplex auto

# Adiciona a porta do AP na VLAN 10
echo switchport trunk allowed vlan add 10
echo -e "exit\n"

# Adiciona porta de switch - switch na VLAN 10
echo interface range FastEthernet0/23-24
echo switchport trunk allowed vlan add 10
echo -e "exit\n"

# Sobe todas as portas a serem utilizadas
# Configuração extra do ultimo Switch requer alterar de 5 para 8
echo interface range FastEthernet0/1-5 # Computadores
echo no shutdown
echo interface FastEthernet0/18 # Acesso
echo no shutdown
echo interface FastEthernet0/20 # AP
echo no shutdown
echo interface range FastEthernet0/23-24 # Switch - Switch
echo no shutdown
echo -e "exit\n"

# Configuração caso nescessite remover o AP
# echo interface FastEthernet0/20
# echo switchport trunk allowed vlan remove 10
# echo speed auto
# echo duplex auto
# echo shutdown
# echo exit

# Salva as modificações feitas
echo -e "exit"
echo -e copy running-config startup-config
