#!/usr/bin/bash


# stanza="interface FastEthernet0/1
# switchport trunk allowed vlan remove 1002
# switchport trunk allowed vlan remove 1003
# switchport trunk allowed vlan remove 1004
# switchport trunk allowed vlan remove 1005
# exit"

# cat <<< $stanza

vlan_ids=(1 10 100{2,3,4,5})

# Derrubar todas as portas
echo interface range FastEthernet0/1-24
echo shutdown
echo exit

# Subir todas as portas
# echo interface range FastEthernet0/1-24
# echo no shutdown

# Joga todas as portas em Trunk
echo interface range FastEthernet0/1-24
echo switchport mode trunk
echo exit

# Remove VLANs de todas as portas
echo interface range FastEthernet0/1-24
for vlan in ${vlan_ids[@]}; do
    echo "switchport trunk allowed vlan remove $vlan"
done
echo exit

# for port in $(seq 1 24); do
#     # Remover varias VLANs
#     echo "interface FastEthernet0/$port"
#     for vlan in ${vlan_ids[@]}; do
#         echo "switchport trunk allowed vlan remove $vlan"
#     done
#     echo "exit"
# done

# Adicionar portas em VLAN 10
echo interface range FastEthernet0/1-5
echo switchport trunk allowed vlan add 10
echo exit

# Configurar portas 10Mb/Half
echo interface range FastEthernet0/1-2
echo speed 10
echo duplex half
echo exit

# Configurar portas 10Mb/Full
echo interface range FastEthernet0/3-5
echo speed 10
echo duplex full
echo exit

# Joga porta 16 em Access
echo interface FastEthernet0/16
echo switchport mode access
